/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import model.LapBuilder;

/**
 *
 * @author chamu
 */
public class Lap extends javax.swing.JFrame {

    /**
     * Creates new form Lap
     */
    private String brand;
    private String Model;
    private int ram;
    private int gpu;
    private String processor;
    private int hardDrive;
    private double screenSize;
    private boolean wifi;
    private boolean bluetooth;
    private String os;

    String msiLogo = "/gui/imgs/msi.png";
    String asusLogo = "/gui/imgs/asus.png";
    String hp1Logo = "/gui/imgs/hp1.png";
    String hp2Logo = "/gui/imgs/hp2.png";
    String dellLogo = "/gui/imgs/dell.png";
    String macLogo = "/gui/imgs/mac.png";

    String linuxLogo = "/gui/imgs/linux.png";
    String windowsLogo = "/gui/imgs/windows.png";
    String macOSLogo = "/gui/imgs/macOS.png";
    

    String i3Logo = "/gui/imgs/i3.png";
    String i5Logo = "/gui/imgs/i5.png";
    String i7Logo = "/gui/imgs/i7_150.png";

    String ry5Logo = "/gui/imgs/ryzen5.png";
    String ry7Logo = "/gui/imgs/ryzen7.png";
    String ry9Logo = "/gui/imgs/ryzen9.png";
    
    String macM1Logo = "/gui/imgs/m1.png";
    String macM2Logo = "/gui/imgs/m2.png";
    

    public Lap() {
        initComponents();

        jPanel3.setVisible(false);
        jPanel15.setVisible(false);
    }

    public Lap(String brand, String Model, int ram, int gpu, String processor, int hardDrive, double screenSize, boolean wifi, boolean bluetooth, String os) {
        this.brand = brand;
        this.Model = Model;
        this.ram = ram;
        this.gpu = gpu;
        this.processor = processor;
        this.hardDrive = hardDrive;
        this.screenSize = screenSize;
        this.wifi = wifi;
        this.bluetooth = bluetooth;
        this.os = os;
    }

    @Override
    public String toString() {
        return brand
                + Model
                + ram
                + gpu
                + processor
                + hardDrive
                + screenSize
                + wifi
                + bluetooth
                + os;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButtonMac = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        m3 = new javax.swing.JRadioButton();
        m1 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        m2 = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton15 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton18 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jRadioButton30 = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jRadioButton25 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jRadioButton29 = new javax.swing.JRadioButton();
        jRadioButton28 = new javax.swing.JRadioButton();
        jPanel15 = new javax.swing.JPanel();
        jLabelMac = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton31 = new javax.swing.JRadioButton();
        jRadioButton32 = new javax.swing.JRadioButton();
        jRadioButton33 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        os1 = new javax.swing.JLabel();
        bluetooth1 = new javax.swing.JLabel();
        os2 = new javax.swing.JLabel();
        bluetooth2 = new javax.swing.JLabel();
        wifi2 = new javax.swing.JLabel();
        screen2 = new javax.swing.JLabel();
        wifi1 = new javax.swing.JLabel();
        screen1 = new javax.swing.JLabel();
        hard1 = new javax.swing.JLabel();
        procesor1 = new javax.swing.JLabel();
        gpu1 = new javax.swing.JLabel();
        ram1 = new javax.swing.JLabel();
        model1 = new javax.swing.JLabel();
        brand1 = new javax.swing.JLabel();
        brand2 = new javax.swing.JLabel();
        model2 = new javax.swing.JLabel();
        ram2 = new javax.swing.JLabel();
        gpu2 = new javax.swing.JLabel();
        procesor2 = new javax.swing.JLabel();
        hard2 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        picPros = new javax.swing.JLabel();
        picBrand = new javax.swing.JLabel();
        picOS = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CheckOut");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, 220, 50));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("MSI");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 50, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("ASUS");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 60, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("HP");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 50, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Brand");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 76, 24));

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setText("DELL");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 60, -1));

        buttonGroup1.add(jRadioButtonMac);
        jRadioButtonMac.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButtonMac.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonMac.setText("Mac");
        jRadioButtonMac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMacActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButtonMac, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 60, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 550, 50));

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup2.add(m3);
        m3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        m3.setForeground(new java.awt.Color(255, 255, 255));
        m3.setText("--------");
        m3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m3ActionPerformed(evt);
            }
        });
        jPanel5.add(m3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        buttonGroup2.add(m1);
        m1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        m1.setForeground(new java.awt.Color(255, 255, 255));
        m1.setText("--------");
        m1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m1ActionPerformed(evt);
            }
        });
        jPanel5.add(m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Model");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 76, 24));

        buttonGroup2.add(m2);
        m2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        m2.setForeground(new java.awt.Color(255, 255, 255));
        m2.setText("--------");
        m2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m2ActionPerformed(evt);
            }
        });
        jPanel5.add(m2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 550, 50));

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup3.add(jRadioButton9);
        jRadioButton9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton9.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton9.setText("32");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 13, -1, -1));

        buttonGroup3.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton8.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton8.setText("16");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 13, -1, -1));

        buttonGroup3.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton7.setText("8");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 13, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("RAM ");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 76, 24));

        buttonGroup3.add(jRadioButton15);
        jRadioButton15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton15.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton15.setText("4");
        jRadioButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton15ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 13, -1, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("GB");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 17, -1, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("GB");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 17, -1, -1));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("GB");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 17, 22, -1));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("GB");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 17, -1, -1));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 550, 50));

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup4.add(jRadioButton12);
        jRadioButton12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton12.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton12.setText("4");
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });
        jPanel7.add(jRadioButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 13, -1, -1));

        buttonGroup4.add(jRadioButton11);
        jRadioButton11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton11.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton11.setText("2");
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });
        jPanel7.add(jRadioButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 13, -1, -1));

        buttonGroup4.add(jRadioButton10);
        jRadioButton10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton10.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton10.setText("1");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });
        jPanel7.add(jRadioButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 13, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("GPU ");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 76, 24));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("GB");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 17, -1, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("GB");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 17, -1, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("GB");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 17, -1, -1));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 550, 50));

        jPanel9.setBackground(new java.awt.Color(102, 102, 102));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup6.add(jRadioButton17);
        jRadioButton17.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton17.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton17.setText("2");
        jRadioButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton17ActionPerformed(evt);
            }
        });
        jPanel9.add(jRadioButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 15, 40, 20));

        buttonGroup6.add(jRadioButton16);
        jRadioButton16.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton16.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton16.setText("1");
        jRadioButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton16ActionPerformed(evt);
            }
        });
        jPanel9.add(jRadioButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 15, -1, 20));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Hard Drive ");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, 24));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TB");
        jPanel9.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 16, 20, 20));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TB");
        jPanel9.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 16, 20, 20));

        buttonGroup6.add(jRadioButton18);
        jRadioButton18.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton18.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton18.setText("500");
        jRadioButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton18ActionPerformed(evt);
            }
        });
        jPanel9.add(jRadioButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 15, -1, 20));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("GB");
        jPanel9.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 16, -1, 20));

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 550, 50));

        jPanel10.setBackground(new java.awt.Color(102, 102, 102));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup7.add(jRadioButton21);
        jRadioButton21.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton21.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton21.setText("15.5");
        jRadioButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton21ActionPerformed(evt);
            }
        });
        jPanel10.add(jRadioButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 16, -1, -1));

        buttonGroup7.add(jRadioButton20);
        jRadioButton20.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton20.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton20.setText("17.5");
        jRadioButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton20ActionPerformed(evt);
            }
        });
        jPanel10.add(jRadioButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 16, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Screen Size ");
        jPanel10.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 16, 127, 24));

        buttonGroup7.add(jRadioButton24);
        jRadioButton24.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton24.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton24.setText("14.5");
        jRadioButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton24ActionPerformed(evt);
            }
        });
        jPanel10.add(jRadioButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 16, -1, -1));

        buttonGroup7.add(jRadioButton27);
        jRadioButton27.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton27.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton27.setText("16.5");
        jRadioButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton27ActionPerformed(evt);
            }
        });
        jPanel10.add(jRadioButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 16, -1, -1));

        buttonGroup7.add(jRadioButton30);
        jRadioButton30.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton30.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton30.setText("13.5");
        jRadioButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton30ActionPerformed(evt);
            }
        });
        jPanel10.add(jRadioButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 16, -1, -1));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("\"");
        jPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 13, -1, -1));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("\"");
        jPanel10.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 13, -1, -1));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("\"");
        jPanel10.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 13, -1, -1));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("\"");
        jPanel10.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 13, -1, -1));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("\"");
        jPanel10.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 13, -1, -1));

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 550, 50));

        jPanel11.setBackground(new java.awt.Color(102, 102, 102));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup8.add(jRadioButton23);
        jRadioButton23.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton23.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton23.setText("No");
        jRadioButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton23ActionPerformed(evt);
            }
        });
        jPanel11.add(jRadioButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        buttonGroup8.add(jRadioButton22);
        jRadioButton22.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton22.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton22.setText("Yes");
        jRadioButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton22ActionPerformed(evt);
            }
        });
        jPanel11.add(jRadioButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Wi-Fi");
        jPanel11.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 76, 24));

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 550, 50));

        jPanel12.setBackground(new java.awt.Color(102, 102, 102));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Bluetooth");
        jPanel12.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 76, 24));

        buttonGroup9.add(jRadioButton25);
        jRadioButton25.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton25.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton25.setText("Yes");
        jRadioButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton25ActionPerformed(evt);
            }
        });
        jPanel12.add(jRadioButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        buttonGroup9.add(jRadioButton26);
        jRadioButton26.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton26.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton26.setText("No");
        jRadioButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton26ActionPerformed(evt);
            }
        });
        jPanel12.add(jRadioButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jPanel2.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 320, 50));

        jPanel13.setBackground(new java.awt.Color(102, 102, 102));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Operating System");
        jPanel13.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 116, 24));

        jPanel16.setBackground(new java.awt.Color(102, 102, 102));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup10.add(jRadioButton29);
        jRadioButton29.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton29.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton29.setText("Linux");
        jRadioButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton29ActionPerformed(evt);
            }
        });
        jPanel16.add(jRadioButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        buttonGroup10.add(jRadioButton28);
        jRadioButton28.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton28.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton28.setText("Windows");
        jRadioButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton28ActionPerformed(evt);
            }
        });
        jPanel16.add(jRadioButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel13.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 190, 30));

        jPanel15.setBackground(new java.awt.Color(102, 102, 102));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelMac.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMac.setText("-------");
        jPanel15.add(jLabelMac, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jPanel13.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 100, 30));

        jPanel2.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 550, 50));

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup5.add(jRadioButton14);
        jRadioButton14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton14.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton14.setText("i3");
        jRadioButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton14ActionPerformed(evt);
            }
        });
        jPanel8.add(jRadioButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 40, -1));

        buttonGroup5.add(jRadioButton13);
        jRadioButton13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton13.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton13.setText("i5");
        jRadioButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton13ActionPerformed(evt);
            }
        });
        jPanel8.add(jRadioButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 40, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Processor");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 76, 24));

        buttonGroup5.add(jRadioButton19);
        jRadioButton19.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton19.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton19.setText("Ryzen 9");
        jRadioButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton19ActionPerformed(evt);
            }
        });
        jPanel8.add(jRadioButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        buttonGroup5.add(jRadioButton31);
        jRadioButton31.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton31.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton31.setText("i7");
        jRadioButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton31ActionPerformed(evt);
            }
        });
        jPanel8.add(jRadioButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 40, -1));

        buttonGroup5.add(jRadioButton32);
        jRadioButton32.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton32.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton32.setText("Ryzen 5");
        jRadioButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton32ActionPerformed(evt);
            }
        });
        jPanel8.add(jRadioButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        buttonGroup5.add(jRadioButton33);
        jRadioButton33.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton33.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton33.setText("Ryzen 7");
        jRadioButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton33ActionPerformed(evt);
            }
        });
        jPanel8.add(jRadioButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 550, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 32, 610, 610));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        os1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        os1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(os1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 190, 24));

        bluetooth1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bluetooth1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(bluetooth1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 180, 24));

        os2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        os2.setForeground(new java.awt.Color(255, 255, 255));
        os2.setText("Operating System");
        jPanel3.add(os2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 116, 24));

        bluetooth2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bluetooth2.setForeground(new java.awt.Color(255, 255, 255));
        bluetooth2.setText("Bluetooth");
        jPanel3.add(bluetooth2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 76, 24));

        wifi2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        wifi2.setForeground(new java.awt.Color(255, 255, 255));
        wifi2.setText("Wi-Fi");
        jPanel3.add(wifi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 76, 24));

        screen2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        screen2.setForeground(new java.awt.Color(255, 255, 255));
        screen2.setText("Screen Size (inches)");
        jPanel3.add(screen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 127, 24));

        wifi1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        wifi1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(wifi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 180, 24));

        screen1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        screen1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(screen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 180, 24));

        hard1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        hard1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(hard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 170, 24));

        procesor1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        procesor1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(procesor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 130, 24));

        gpu1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        gpu1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(gpu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 130, 24));

        ram1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ram1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(ram1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 130, 24));

        model1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        model1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(model1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 130, 24));

        brand1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        brand1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(brand1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 180, 24));

        brand2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        brand2.setForeground(new java.awt.Color(255, 255, 255));
        brand2.setText("Brand");
        jPanel3.add(brand2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 76, 24));

        model2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        model2.setForeground(new java.awt.Color(255, 255, 255));
        model2.setText("Model");
        jPanel3.add(model2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 76, 24));

        ram2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ram2.setForeground(new java.awt.Color(255, 255, 255));
        ram2.setText("RAM (GB)");
        jPanel3.add(ram2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 76, 24));

        gpu2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        gpu2.setForeground(new java.awt.Color(255, 255, 255));
        gpu2.setText("GPU (GB)");
        jPanel3.add(gpu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 76, 24));

        procesor2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        procesor2.setForeground(new java.awt.Color(255, 255, 255));
        procesor2.setText("Processor");
        jPanel3.add(procesor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 76, 24));

        hard2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        hard2.setForeground(new java.awt.Color(255, 255, 255));
        hard2.setText("Hard Drive");
        jPanel3.add(hard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 91, 24));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, 480, 380));

        jPanel14.setBackground(new java.awt.Color(102, 102, 102));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        picPros.setText("               ");
        jPanel14.add(picPros, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 180, 120));

        picBrand.setText("               ");
        jPanel14.add(picBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, 120));

        picOS.setText("               ");
        jPanel14.add(picOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 180, 120));

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 580, 150));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        brand = jRadioButton1.getText();

        m1.setText("Pro");
        m2.setText("Zenbook");
        m3.setText("Vivabook");

        m1.setVisible(true);
        m2.setVisible(true);
        m3.setVisible(true);

        picBrand.setIcon(new javax.swing.ImageIcon(getClass().getResource(asusLogo)));

        jPanel15.setVisible(false);
        jPanel16.setVisible(true);

        jRadioButton14.setText("i3");
        jRadioButton13.setText("i5");
        jRadioButton31.setText("i7");
        jRadioButton32.setText("Ryzen5");
        jRadioButton33.setText("Ryzen7");
        jRadioButton19.setText("Ryzen9");

        jRadioButton14.setVisible(true);
        jRadioButton13.setVisible(true);
        jRadioButton31.setVisible(true);
        jRadioButton32.setVisible(true);
        jRadioButton33.setVisible(true);
        jRadioButton19.setVisible(true);

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        brand = jRadioButton2.getText();

        m1.setText("OMEN");
        m2.setText("ENVY");
        m3.setText("Spector");

        m1.setVisible(true);
        m2.setVisible(true);
        m3.setVisible(true);

        picBrand.setIcon(new javax.swing.ImageIcon(getClass().getResource(hp2Logo)));

        jPanel15.setVisible(false);
        jPanel16.setVisible(true);

        jRadioButton14.setText("i3");
        jRadioButton13.setText("i5");
        jRadioButton31.setText("i7");
        jRadioButton32.setText("Ryzen5");
        jRadioButton33.setText("Ryzen7");
        jRadioButton19.setText("Ryzen9");

        jRadioButton14.setVisible(true);
        jRadioButton13.setVisible(true);
        jRadioButton31.setVisible(true);
        jRadioButton32.setVisible(true);
        jRadioButton33.setVisible(true);
        jRadioButton19.setVisible(true);


    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        brand = jRadioButton3.getText();

        m1.setText("Raider");
        m2.setText("Vector");
        m3.setText("Stelth");

        m1.setVisible(true);
        m2.setVisible(true);
        m3.setVisible(true);

        picBrand.setIcon(new javax.swing.ImageIcon(getClass().getResource(msiLogo)));

        jPanel15.setVisible(false);
        jPanel16.setVisible(true);

        jRadioButton14.setText("i3");
        jRadioButton13.setText("i5");
        jRadioButton31.setText("i7");
        jRadioButton32.setText("Ryzen5");
        jRadioButton33.setText("Ryzen7");
        jRadioButton19.setText("Ryzen9");

        jRadioButton14.setVisible(true);
        jRadioButton13.setVisible(true);
        jRadioButton31.setVisible(true);
        jRadioButton32.setVisible(true);
        jRadioButton33.setVisible(true);
        jRadioButton19.setVisible(true);


    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void m1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m1ActionPerformed
        // TODO add your handling code here:

        Model = m1.getText();
    }//GEN-LAST:event_m1ActionPerformed

    private void m3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m3ActionPerformed
        // TODO add your handling code here:
        Model = m3.getText();
    }//GEN-LAST:event_m3ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
        ram = Integer.parseInt(jRadioButton7.getText());
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
        ram = Integer.parseInt(jRadioButton8.getText());
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:
        ram = Integer.parseInt(jRadioButton9.getText());
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        // TODO add your handling code here:
        gpu = Integer.parseInt(jRadioButton10.getText());
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        // TODO add your handling code here:
        gpu = Integer.parseInt(jRadioButton11.getText());
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        // TODO add your handling code here:
        gpu = Integer.parseInt(jRadioButton12.getText());
    }//GEN-LAST:event_jRadioButton12ActionPerformed

    private void jRadioButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton13ActionPerformed
        // TODO add your handling code here:
        processor = jRadioButton13.getText();

        picPros.setIcon(new javax.swing.ImageIcon(getClass().getResource(i5Logo)));

       
    }//GEN-LAST:event_jRadioButton13ActionPerformed

    private void jRadioButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton14ActionPerformed
        // TODO add your handling code here:
        processor = jRadioButton14.getText();

        picPros.setIcon(new javax.swing.ImageIcon(getClass().getResource(i3Logo)));

        if (jRadioButtonMac.isSelected()) {

            picPros.setIcon(new javax.swing.ImageIcon(getClass().getResource(macM1Logo)));

        }
    }//GEN-LAST:event_jRadioButton14ActionPerformed

    private void jRadioButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton16ActionPerformed
        // TODO add your handling code here:
        hardDrive = Integer.parseInt(jRadioButton16.getText());
    }//GEN-LAST:event_jRadioButton16ActionPerformed

    private void jRadioButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton17ActionPerformed
        // TODO add your handling code here:
        hardDrive = Integer.parseInt(jRadioButton17.getText());
    }//GEN-LAST:event_jRadioButton17ActionPerformed

    private void jRadioButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton21ActionPerformed
        // TODO add your handling code here:
        screenSize = Double.parseDouble(jRadioButton21.getText());
    }//GEN-LAST:event_jRadioButton21ActionPerformed

    private void jRadioButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton22ActionPerformed
        // TODO add your handling code here:
        wifi = Boolean.parseBoolean(jRadioButton22.getText());
    }//GEN-LAST:event_jRadioButton22ActionPerformed

    private void jRadioButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton23ActionPerformed
        // TODO add your handling code here:
        wifi = Boolean.parseBoolean(jRadioButton23.getText());
    }//GEN-LAST:event_jRadioButton23ActionPerformed

    private void jRadioButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton25ActionPerformed
        // TODO add your handling code here:
        bluetooth = Boolean.parseBoolean(jRadioButton25.getText());
    }//GEN-LAST:event_jRadioButton25ActionPerformed

    private void jRadioButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton26ActionPerformed
        // TODO add your handling code here:
        bluetooth = Boolean.parseBoolean(jRadioButton26.getText());
    }//GEN-LAST:event_jRadioButton26ActionPerformed

    private void jRadioButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton28ActionPerformed
        // TODO add your handling code here:
        os = jRadioButton28.getText();

        picOS.setIcon(new javax.swing.ImageIcon(getClass().getResource(windowsLogo)));
    }//GEN-LAST:event_jRadioButton28ActionPerformed

    private void jRadioButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton29ActionPerformed
        // TODO add your handling code here:
        os = jRadioButton29.getText();

        picOS.setIcon(new javax.swing.ImageIcon(getClass().getResource(linuxLogo)));
    }//GEN-LAST:event_jRadioButton29ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Lap lapObj = new LapBuilder().setBrand(brand).setModel(Model).setRam(ram).setGpu(gpu).setProcessor(processor).
                setHardDrive(hardDrive).setScreenSize(screenSize).setWifi(wifi).setBluetooth(bluetooth).setOs(os).getLap();

        System.out.println(lapObj);

        if (brand != null) {

            brand1.setText(brand);

        } else {
            brand1.setText("- - - - - - - - - - - -");
        }

        if (Model != null) {

            model1.setText(Model);

        } else {
            model1.setText("- - - - - - - - - - - -");
        }

        if (ram != 0) {

            ram1.setText(ram + " GB");

        } else {
            ram1.setText("- - - - - - - - - - - -");
        }

        if (gpu != 0) {

            gpu1.setText(gpu + " GB");

        } else {
            gpu1.setText("- - - - - - - - - - - -");
        }

        if (processor != null) {

            procesor1.setText(processor);

        } else {
            procesor1.setText("- - - - - - - - - - - -");
        }

        if (hardDrive != 0) {

            hard1.setText(hardDrive + " GB");

        } else {
            hard1.setText("- - - - - - - - - - - -");
        }

        if (screenSize != 0) {

            screen1.setText(screenSize + " inches");

        } else {
            screen1.setText("- - - - - - - - - - - -");
        }

        if (jRadioButton22.isSelected()) {
            wifi1.setText("✓");
        } else {
            wifi1.setText("❌");
        }
        if (jRadioButton25.isSelected()) {
            bluetooth1.setText("✓");
        } else {
            bluetooth1.setText("❌");
        }

        if (os != null) {

            os1.setText(os);

        } else if (jRadioButtonMac.isSelected()) {
            os1.setText("Mac OS");

        } else {
            os1.setText("- - - - - - - - - - - -");
        }

        jPanel3.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton18ActionPerformed
        // TODO add your handling code here:

        hardDrive = Integer.parseInt(jRadioButton18.getText());
    }//GEN-LAST:event_jRadioButton18ActionPerformed

    private void jRadioButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton15ActionPerformed
        // TODO add your handling code here:

        ram = Integer.parseInt(jRadioButton15.getText());
    }//GEN-LAST:event_jRadioButton15ActionPerformed

    private void jRadioButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton24ActionPerformed
        // TODO add your handling code here:
        screenSize = Double.parseDouble(jRadioButton24.getText());
    }//GEN-LAST:event_jRadioButton24ActionPerformed

    private void jRadioButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton30ActionPerformed
        // TODO add your handling code here:

        screenSize = Double.parseDouble(jRadioButton30.getText());
    }//GEN-LAST:event_jRadioButton30ActionPerformed

    private void jRadioButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton27ActionPerformed
        // TODO add your handling code here:
        screenSize = Double.parseDouble(jRadioButton27.getText());
    }//GEN-LAST:event_jRadioButton27ActionPerformed

    private void jRadioButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton20ActionPerformed
        // TODO add your handling code here:
        screenSize = Double.parseDouble(jRadioButton20.getText());
    }//GEN-LAST:event_jRadioButton20ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
        brand = jRadioButton6.getText();

        m1.setText("XPS");
        m2.setText("Latitude");
        m3.setText("Inspiron");

        m1.setVisible(true);
        m2.setVisible(true);
        m3.setVisible(true);

        picBrand.setIcon(new javax.swing.ImageIcon(getClass().getResource(dellLogo)));

        jPanel15.setVisible(false);
        jPanel16.setVisible(true);

        jRadioButton14.setText("i3");
        jRadioButton13.setText("i5");
        jRadioButton31.setText("i7");
        jRadioButton32.setText("Ryzen5");
        jRadioButton33.setText("Ryzen7");
        jRadioButton19.setText("Ryzen9");

        jRadioButton14.setVisible(true);
        jRadioButton13.setVisible(true);
        jRadioButton31.setVisible(true);
        jRadioButton32.setVisible(true);
        jRadioButton33.setVisible(true);
        jRadioButton19.setVisible(true);

    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton19ActionPerformed
        // TODO add your handling code here:
        processor = jRadioButton19.getText();

        picPros.setIcon(new javax.swing.ImageIcon(getClass().getResource(ry9Logo)));

    }//GEN-LAST:event_jRadioButton19ActionPerformed

    private void jRadioButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton31ActionPerformed
        // TODO add your handling code here:

        processor = jRadioButton31.getText();

        picPros.setIcon(new javax.swing.ImageIcon(getClass().getResource(i7Logo)));
        
         if (jRadioButtonMac.isSelected()) {

            picPros.setIcon(new javax.swing.ImageIcon(getClass().getResource(macM2Logo)));

        }
    }//GEN-LAST:event_jRadioButton31ActionPerformed

    private void jRadioButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton32ActionPerformed
        // TODO add your handling code here:

        processor = jRadioButton32.getText();

        picPros.setIcon(new javax.swing.ImageIcon(getClass().getResource(ry5Logo)));
    }//GEN-LAST:event_jRadioButton32ActionPerformed

    private void jRadioButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton33ActionPerformed
        // TODO add your handling code here:

        processor = jRadioButton33.getText();

        picPros.setIcon(new javax.swing.ImageIcon(getClass().getResource(ry7Logo)));
    }//GEN-LAST:event_jRadioButton33ActionPerformed

    private void m2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m2ActionPerformed
        // TODO add your handling code here:

        Model = m2.getText();
    }//GEN-LAST:event_m2ActionPerformed

    private void jRadioButtonMacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMacActionPerformed
        // TODO add your handling code here:

        brand = jRadioButtonMac.getText();

        picBrand.setIcon(new javax.swing.ImageIcon(getClass().getResource(macLogo)));
        picOS.setIcon(new javax.swing.ImageIcon(getClass().getResource(macOSLogo)));
        

        m1.setText("MacBook Pro");
        m2.setVisible(false);
        m3.setText("MacBook Air");

        jPanel15.setVisible(true);
        jPanel16.setVisible(false);

        jLabelMac.setText("Mac OS");

        jRadioButton14.setText("M1");
        jRadioButton13.setVisible(false);
        jRadioButton31.setText("M2");
        jRadioButton32.setVisible(false);
        jRadioButton33.setVisible(false);
        jRadioButton19.setVisible(false);


    }//GEN-LAST:event_jRadioButtonMacActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lap().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bluetooth1;
    private javax.swing.JLabel bluetooth2;
    private javax.swing.JLabel brand1;
    private javax.swing.JLabel brand2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JLabel gpu1;
    private javax.swing.JLabel gpu2;
    private javax.swing.JLabel hard1;
    private javax.swing.JLabel hard2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMac;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JRadioButton jRadioButton32;
    private javax.swing.JRadioButton jRadioButton33;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JRadioButton jRadioButtonMac;
    private javax.swing.JRadioButton m1;
    private javax.swing.JRadioButton m2;
    private javax.swing.JRadioButton m3;
    private javax.swing.JLabel model1;
    private javax.swing.JLabel model2;
    private javax.swing.JLabel os1;
    private javax.swing.JLabel os2;
    private javax.swing.JLabel picBrand;
    private javax.swing.JLabel picOS;
    private javax.swing.JLabel picPros;
    private javax.swing.JLabel procesor1;
    private javax.swing.JLabel procesor2;
    private javax.swing.JLabel ram1;
    private javax.swing.JLabel ram2;
    private javax.swing.JLabel screen1;
    private javax.swing.JLabel screen2;
    private javax.swing.JLabel wifi1;
    private javax.swing.JLabel wifi2;
    // End of variables declaration//GEN-END:variables
}
